### ISSUE TITLE
was working great now  getting error

### ISSUE THREAD

**Issue by Tw1zT3d2four7** [honest-mule/Drive2CloudSync#1]
C:\Media-Server\Drive2CloudSync-main>cd C:\Media-Server\Drive2CloudSync-main

C:\Media-Server\Drive2CloudSync-main>.\cataloguer.py -x
Traceback (most recent call last):
  File "C:\Media-Server\Drive2CloudSync-main\cataloguer.py", line 403, in <module>
    downloads = sort_downloads(get_downloads())
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Media-Server\Drive2CloudSync-main\cataloguer.py", line 306, in sort_downloads
    for link in _dict:
RuntimeError: dictionary changed size during iteration

C:\Media-Server\Drive2CloudSync-main>pause
Press any key to continue . . .

Pay no mind to the PAUSE I added it to the .bat so I could see why it was closing the cmd. the issue started after I deleted the .db in cache folder and the status.log to start fresh. However its been this error everytime I run the script now? any help would be great!

**Comment by honest-mule** [comment]
What do you have in your `status.log` file? Any errors/exceptions there?

Possibly real-debrid doesn't like your API key.

**Comment by honest-mule** [comment]
First place I would like to start is to make sure that your real-debrid API key is valid, please run this script in your local (replace XXXX with your API key):

```py
import requests

url = "https://api.real-debrid.com/rest/1.0/torrents?limit=10&page=1"

payload={}
headers = {
  'Authorization': 'Bearer XXXXX'
}

response = requests.request("GET", url, headers=headers, data=payload)

print(response.text)
```

Let me know if real-debrid is replying normally to you with your API key. In case the key is good, then from your error it's likely that the `sort_downloads()` is not able to handle some torrent information.

So in that case, please try replacing the `sort_downloads()` function in the `cataloguer.py` file with this:

```py
def sort_downloads(downloads = [], _dict = {}):
    try:
        for download_info in downloads:
            _dict[download_info["link"]] = download_info
        for link in _dict:
            if is_expired(_dict[link]["generated"]):
                del _dict[link]
        return _dict
    except Exception as e:
        print(f"ERROR: sort_downloads exception - {e}")
```

and then provide me with whatever exception information it outputs.

Moreover, if you've added something to the `corrections.csv` files, please provide the contents of that file here as well.

**Comment by Tw1zT3d2four7** [comment]
that fixed it and its working again. here is the log.

2023-10-14 00:05:50,652 : ERROR : __main__ : Unable to load corrections
	Exception Info: ValueError: invalid literal for int() with base 10: 'tmdb_id'
	Traceback (most recent call last):
	  File "C:\Media-Server\Drive2CloudSync-main\cataloguer.py", line 380, in manage_corrections
	    correction = Correction(tmdb_id=_values[0].strip(),
	                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
	  File "C:\Media-Server\Drive2CloudSync-main\utils.py", line 139, in __init__
	    self.tmdb_id = int(tmdb_id)
	                   ^^^^^^^^^^^^
	ValueError: invalid literal for int() with base 10: 'tmdb_id'
2023-10-14 00:05:50,652 : ERROR : __main__ : Unable to load corrections
	Exception Info: ValueError: invalid literal for int() with base 10: 'tmdb_id'
	Traceback (most recent call last):
	  File "C:\Media-Server\Drive2CloudSync-main\cataloguer.py", line 380, in manage_corrections
	    correction = Correction(tmdb_id=_values[0].strip(),
	                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
	  File "C:\Media-Server\Drive2CloudSync-main\utils.py", line 139, in __init__
	    self.tmdb_id = int(tmdb_id)
	                   ^^^^^^^^^^^^
	ValueError: invalid literal for int() with base 10: 'tmdb_id'
2023-10-14 00:05:53,065 : INFO : __main__ : Direct link generated:
	Torrent: Yellowjackets (2021) Season 2 S02 (1080p AMZN WEB-DL x265 HEVC 10bit EAC3 5.1 Ghost)
	Path: /Yellowjackets (2021) - S02E07 - Burial (1080p AMZN WEB-DL x265 Ghost).mkv
	Link: https://mia3.download.real-debrid.com/d/FOSS33HEKGH7Q23/Yellowjackets%20%282021%29%20-%20S02E07%20-%20Burial%20%281080p%20AMZN%20WEB-DL%20x265%20Ghost%29.mkv
2023-10-14 00:05:54,090 : INFO : __main__ : Direct link generated:
	Torrent: Yellowjackets (2021) Season 2 S02 (1080p AMZN WEB-DL x265 HEVC 10bit EAC3 5.1 Ghost)
	Path: /Yellowjackets (2021) - S02E08 - It Chooses (1080p AMZN WEB-DL x265 Ghost).mkv
	Link: https://mia3.download.real-debrid.com/d/W4CSBDEEPHBIG23/Yellowjackets%20%282021%29%20-%20S02E08%20-%20It%20Chooses%20%281080p%20AMZN%20WEB-DL%20x265%20Ghost%29.mkv
2023-10-14 00:05:55,135 : INFO : __main__ : Direct link generated:
	Torrent: Yellowjackets (2021) Season 2 S02 (1080p AMZN WEB-DL x265 HEVC 10bit EAC3 5.1 Ghost)
	Path: /Yellowjackets (2021) - S02E09 - Storytelling (1080p AMZN WEB-DL x265 Ghost).mkv
	Link: https://mia3.download.real-debrid.com/d/4CCCOTY6BJKDK23/Yellowjackets%20%282021%29%20-%20S02E09%20-%20Storytelling%20%281080p%20AMZN%20WEB-DL%20x265%20Ghost%29.mkv
2023-10-14 00:05:57,313 : INFO : __main__ : Direct link generated:
	Torrent: Yellowstone.(2018).Season.01.S01.(1080p AMZN WEB-DL x265 HEVC 10bit AC3 Qman) [UTR]
	Path: /Yellowstone S01E08 (1080p AMZN WEB-DL x265 HEVC 10bit AC3 2.0 Qman) [UTR]/Yellowstone.S01E08.1080p.AMZN.WEB-DL.x265.10bit.EAC3.2.0-Qman[UTR].mkv
	Link: https://mia3.download.real-debrid.com/d/56B3ME2Q25IX423/Yellowstone.S01E08.1080p.AMZN.WEB-DL.x265.10bit.EAC3.2.0-Qman%5BUTR%5D.mkv
2023-10-14 00:05:58,350 : INFO : __main__ : Direct link generated:
	Torrent: Yellowstone.(2018).Season.01.S01.(1080p AMZN WEB-DL x265 HEVC 10bit AC3 Qman) [UTR]
	Path: /Yellowstone S01E09 (1080p AMZN WEB-DL x265 HEVC 10bit AC3 2.0 Qman) [UTR]/Yellowstone.S01E09.1080p.AMZN.WEB-DL.x265.10bit.EAC3.2.0-Qman[UTR].mkv
	Link: https://mia3.download.real-debrid.com/d/GCHY65OS5F43M23/Yellowstone.S01E09.1080p.AMZN.WEB-DL.x265.10bit.EAC3.2.0-Qman%5BUTR%5D.mkv
2023-10-14 00:05:59,359 : INFO : __main__ : Direct link generated:
	Torrent: Yellowstone.(2018).Season.01.S01.(1080p AMZN WEB-DL x265 HEVC 10bit AC3 Qman) [UTR]
	Path: /Yellowstone.2018.S01E01.Daybreak.1080p.AMZN.WEB-DL.x265.10bit.EAC3.6.0-Qman[UTR].mkv
	Link: https://mia4.download.real-debrid.com/d/RKSXBAZEOHSNO42/Yellowstone.2018.S01E01.Daybreak.1080p.AMZN.WEB-DL.x265.10bit.EAC3.6.0-Qman%5BUTR%5D.mkv
2023-10-14 00:06:00,654 : INFO : __main__ : Found best match for Avatar.The.Way.of.Water.2022.1080p.WEBRip.10Bit.DDP5.1.x265-Asiimov.mkv -
	TMDB_ID: 76600
	Title: Avatar: The Way of Water
	OG title: Avatar: The Way of Water
2023-10-14 00:06:01,788 : INFO : __main__ : Found best match for Indiana.Jones.and.the.Dial.of.Destiny.2023.1080p.WEB-DL.DDP5.1.Atmos.H.264-XEBEC[TGx] -
	TMDB_ID: 335977
	Title: Indiana Jones and the Dial of Destiny
	OG title: Indiana Jones and the Dial of Destiny
2023-10-14 00:06:02,939 : INFO : __main__ : Found best match for Fast.X.2023.1080p.AMZN.WEBRip.1600MB.DD5.1.x264-GalaxyRG.mkv -
	TMDB_ID: 385687
	Title: Fast X
	OG title: Fast X
2023-10-14 00:06:04,078 : INFO : __main__ : Found best match for Muzzle.2023.1080p.WEB-DL.DDP5.1.x264-AOC[TGx] -
	TMDB_ID: 939335
	Title: Muzzle
	OG title: Muzzle
2023-10-14 00:06:05,282 : INFO : __main__ : Found best match for Talk.to.Me.2022.1080p.WEB-DL.DDP5.1.H.264-FLUX.mkv -
	TMDB_ID: 1008042
	Title: Talk to Me
	OG title: Talk to Me
2023-10-14 00:06:06,455 : INFO : __main__ : Found best match for The Nun II (2023) [1080p] [WEBRip] [5.1] [YTS.MX] -
	TMDB_ID: 968051
	Title: The Nun II
	OG title: The Nun II
2023-10-14 00:06:07,604 : INFO : __main__ : Found best match for 57.Seconds.2023.1080p.WEB-DL.DDP5.1.H264-EniaHD[TGx] -
	TMDB_ID: 937249
	Title: 57 Seconds
	OG title: 57 Seconds
2023-10-14 00:06:08,777 : INFO : __main__ : Found best match for The.Burial.2023.1080p.WEB.H264-HUZZAH[TGx] -
	TMDB_ID: 763165
	Title: The Burial
	OG title: The Burial
2023-10-14 00:11:31,680 : ERROR : __main__ : Unable to load corrections
	Exception Info: ValueError: invalid literal for int() with base 10: 'tmdb_id'
	Traceback (most recent call last):
	  File "C:\Media-Server\Drive2CloudSync-main\cataloguer.py", line 380, in manage_corrections
	    correction = Correction(tmdb_id=_values[0].strip(),
	                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
	  File "C:\Media-Server\Drive2CloudSync-main\utils.py", line 139, in __init__
	    self.tmdb_id = int(tmdb_id)
	                   ^^^^^^^^^^^^
	ValueError: invalid literal for int() with base 10: 'tmdb_id'
2023-10-14 00:11:31,681 : ERROR : __main__ : Unable to load corrections
	Exception Info: ValueError: invalid literal for int() with base 10: 'tmdb_id'
	Traceback (most recent call last):
	  File "C:\Media-Server\Drive2CloudSync-main\cataloguer.py", line 380, in manage_corrections
	    correction = Correction(tmdb_id=_values[0].strip(),
	                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
	  File "C:\Media-Server\Drive2CloudSync-main\utils.py", line 139, in __init__
	    self.tmdb_id = int(tmdb_id)
	                   ^^^^^^^^^^^^
	ValueError: invalid literal for int() with base 10: 'tmdb_id'
2023-10-14 00:16:47,360 : ERROR : __main__ : Unable to load corrections
	Exception Info: ValueError: invalid literal for int() with base 10: 'tmdb_id'
	Traceback (most recent call last):
	  File "C:\Media-Server\Drive2CloudSync-main\cataloguer.py", line 380, in manage_corrections
	    correction = Correction(tmdb_id=_values[0].strip(),
	                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
	  File "C:\Media-Server\Drive2CloudSync-main\utils.py", line 139, in __init__
	    self.tmdb_id = int(tmdb_id)
	                   ^^^^^^^^^^^^
	ValueError: invalid literal for int() with base 10: 'tmdb_id'
2023-10-14 00:16:47,362 : ERROR : __main__ : Unable to load corrections
	Exception Info: ValueError: invalid literal for int() with base 10: 'tmdb_id'
	Traceback (most recent call last):
	  File "C:\Media-Server\Drive2CloudSync-main\cataloguer.py", line 380, in manage_corrections
	    correction = Correction(tmdb_id=_values[0].strip(),
	                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
	  File "C:\Media-Server\Drive2CloudSync-main\utils.py", line 139, in __init__
	    self.tmdb_id = int(tmdb_id)
	                   ^^^^^^^^^^^^
	ValueError: invalid literal for int() with base 10: 'tmdb_id'
2023-10-14 00:18:51,494 : ERROR : __main__ : Unable to load corrections
	Exception Info: ValueError: invalid literal for int() with base 10: 'tmdb_id'
	Traceback (most recent call last):
	  File "C:\Media-Server\Drive2CloudSync-main\cataloguer.py", line 380, in manage_corrections
	    correction = Correction(tmdb_id=_values[0].strip(),
	                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
	  File "C:\Media-Server\Drive2CloudSync-main\utils.py", line 139, in __init__
	    self.tmdb_id = int(tmdb_id)
	                   ^^^^^^^^^^^^
	ValueError: invalid literal for int() with base 10: 'tmdb_id'
2023-10-14 00:18:51,495 : ERROR : __main__ : Unable to load corrections
	Exception Info: ValueError: invalid literal for int() with base 10: 'tmdb_id'
	Traceback (most recent call last):
	  File "C:\Media-Server\Drive2CloudSync-main\cataloguer.py", line 380, in manage_corrections
	    correction = Correction(tmdb_id=_values[0].strip(),
	                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
	  File "C:\Media-Server\Drive2CloudSync-main\utils.py", line 139, in __init__
	    self.tmdb_id = int(tmdb_id)
	                   ^^^^^^^^^^^^
	ValueError: invalid literal for int() with base 10: 'tmdb_id'

**Comment by honest-mule** [comment]
The first error is gone and now the script is trying to parse your `corrections.csv` but isn't able to because probably it's been formatted wrong. Can you show the contents of it here?

The original error which you mentioned in the first post is due to a bug in `sort_downloads` function. I'll be pushing a fix soon and then you can pull the changes and let me know if you face any other issues.

**Comment by Tw1zT3d2four7** [comment]
> The first error is gone and now the script is trying to parse your `corrections.csv` but isn't able to because probably it's been formatted wrong. Can you show the contents of it here?
> 
> The original error which you mentioned in the first post is due to a bug in `sort_downloads` function. I'll be pushing a fix soon and then you can pull the changes and let me know if you face any other issues.

ok i have not added anything to the correction,csv theres to default lines in it i assume you placed there, what do i need to put there?

tmdb_id,movie,rcloneRD_drive_folder1
tmdb_id,tv,rcloneRD_drive_folder2

however i am using official rclone and it only has two folder named links and torrents. i assume the folder 1 and 2 referr to movies and tv in rclone_rd?

**Comment by honest-mule** [comment]
Then either delete or remove all content from the `corrections.csv` file.

Here's the format for `corrections.csv` if you ever intend to use it in the future:
```csv
tmdb_id,movie,torrent_hash1
tmdb_id,tv,torrent_hash2
```

>however i am using official rclone and it only has two folder named links and torrents. i assume the folder 1 and 2 referr to movies and tv in rclone_rd?

That was the old format for `corrections.csv` file, don't worry about it anymore, it's not used anymore.

**Comment by Tw1zT3d2four7** [comment]
ValueError: invalid literal for int() with base 10: 'tmdb_id'
2023-10-15 18:15:47,035 : ERROR : __main__ : Unable to load corrections
	Exception Info: ValueError: invalid literal for int() with base 10: 'tmdb_id'
	Traceback (most recent call last):
	  File "C:\Media-Server\Drive2CloudSync-main\cataloguer.py", line 380, in manage_corrections
	    correction = Correction(tmdb_id=_values[0].strip(),
	                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
	  File "C:\Media-Server\Drive2CloudSync-main\utils.py", line 139, in __init__
	    self.tmdb_id = int(tmdb_id)
	                   ^^^^^^^^^^^^
	ValueError: invalid literal for int() with base 10: 'tmdb_id'
2023-10-15 18:15:53,466 : WARNING : __main__ : Skipping shows\Riverdale.US.S03.1080p.BluRay.x265-RARBG since TMDB returned 0 results
2023-10-15 18:15:55,709 : WARNING : __main__ : Skipping shows\The Umbrella Academy - Season 3 (2022) since TMDB returned 0 results
2023-10-15 18:16:01,805 : WARNING : __main__ : Skipping default\The.Good.Doctor since its an unknown entity
2023-10-15 18:16:04,282 : WARNING : __main__ : Skipping default\1080p since its an unknown entity
2023-10-15 18:17:04,780 : WARNING : __main__ : Skipping movies\Along Came a Spider (2001)(Remastered)(FHD)(x264)(1080p)(BluRay)(English-CZ) PHDTeam 2022.mkv since TMDB returned 0 results
2023-10-15 18:18:28,511 : WARNING : __main__ : Skipping shows\The Last of Us - Season 1 (2022) since TMDB returned 0 results


Replaced the old two lines in the corrections.csv with what you provided just c&p it and restarted the app thats what i am get in the status.log also is there any way you could add or change it from creating .strm files and just create symlinks to the files on rclone mount of real debrid?

**Comment by Tw1zT3d2four7** [comment]
what i need is a script/app that will watch the rclone mount folder foe real debrid and create symlinks of each file/folder into a directory outside of rclones mount directory. also when it creates these symlinks it also restructures  and renames to keep the library neat. then i point plex or emby jeyyfin and those folders. i use yours in a similar way with rclone and plex_debrid along with jellyseer.

**Comment by honest-mule** [comment]
You're getting confused between two files, `corrections.csv` and `corrections.example.csv`.

All files with `.example` in their name are example files and are not to be used with the script as-is.

The example file suggests what formatting to use inside the main `corrections.csv`. If you feed the `corrections.example.csv` contents to the script, it is bound to give you those errors.

**Comment by Tw1zT3d2four7** [comment]
on your latest release i am getting this. any help would be great thanks in advance,


C:\Media-Server\Drive2CloudSync-main>python .\cataloguer.py -x
C:\Media-Server\Drive2CloudSync-main\cataloguer.py:48: SyntaxWarning: invalid escape sequence '\?'
  logger.warning(f"Skipping movies\??? since torrent object is empty")
C:\Media-Server\Drive2CloudSync-main\cataloguer.py:53: SyntaxWarning: invalid escape sequence '\{'
  logger.warning(f"Skipping movies\{torrent['filename']} since Real-Debrid API returned without relevant torrent info")
C:\Media-Server\Drive2CloudSync-main\cataloguer.py:76: SyntaxWarning: invalid escape sequence '\{'
  logger.warning(f"Skipping movies\{torrent['filename']} since TMDB returned 0 results")
C:\Media-Server\Drive2CloudSync-main\cataloguer.py:136: SyntaxWarning: invalid escape sequence '\?'
  logger.warning(f"Skipping shows\??? since torrent object is empty")
C:\Media-Server\Drive2CloudSync-main\cataloguer.py:141: SyntaxWarning: invalid escape sequence '\{'
  logger.warning(f"Skipping shows\{torrent['filename']} since Real-Debrid API returned without relevant torrent info")
C:\Media-Server\Drive2CloudSync-main\cataloguer.py:164: SyntaxWarning: invalid escape sequence '\{'
  logger.warning(f"Skipping shows\{torrent['filename']} since TMDB returned 0 results")
C:\Media-Server\Drive2CloudSync-main\cataloguer.py:271: SyntaxWarning: invalid escape sequence '\{'
  logger.warning(f"Skipping default\{torrent['filename']} since its an unknown entity")
C:\Media-Server\Drive2CloudSync-main\cataloguer.py:364: SyntaxWarning: invalid escape sequence '\{'
  logger.error(f"{type}\{torrent['filename']} could not be resolved\n\tDetails: {ex_string}")
unable to open database file
Traceback (most recent call last):
  File "C:\Media-Server\Drive2CloudSync-main\cataloguer.py", line 41, in <module>
    cache = Cache(logger)
            ^^^^^^^^^^^^^
  File "C:\Media-Server\Drive2CloudSync-main\cache.py", line 20, in __init__
    self.create_table()
  File "C:\Media-Server\Drive2CloudSync-main\cache.py", line 32, in create_table
    c = self.conn.cursor()
        ^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'cursor'

C:\Media-Server\Drive2CloudSync-main>pause
Press any key to continue . . .

**Comment by honest-mule** [comment]
I've just a pushed fix for this issue. Please pull the latest changes and try again.

**Comment by Tw1zT3d2four7** [comment]
program is working but still getting this at the start and it will get a error and freeze/stop? while scanning and has to be restarted. I will try and capture logs of it freezing/stopping.


C:\Media-Server\Drive2CloudSync-main>python .\cataloguer.py -x
C:\Media-Server\Drive2CloudSync-main\cataloguer.py:48: SyntaxWarning: invalid escape sequence '\?'
  logger.warning(f"Skipping movies\??? since torrent object is empty")
C:\Media-Server\Drive2CloudSync-main\cataloguer.py:53: SyntaxWarning: invalid escape sequence '\{'
  logger.warning(f"Skipping movies\{torrent['filename']} since Real-Debrid API returned without relevant torrent info")
C:\Media-Server\Drive2CloudSync-main\cataloguer.py:76: SyntaxWarning: invalid escape sequence '\{'
  logger.warning(f"Skipping movies\{torrent['filename']} since TMDB returned 0 results")
C:\Media-Server\Drive2CloudSync-main\cataloguer.py:136: SyntaxWarning: invalid escape sequence '\?'
  logger.warning(f"Skipping shows\??? since torrent object is empty")
C:\Media-Server\Drive2CloudSync-main\cataloguer.py:141: SyntaxWarning: invalid escape sequence '\{'
  logger.warning(f"Skipping shows\{torrent['filename']} since Real-Debrid API returned without relevant torrent info")
C:\Media-Server\Drive2CloudSync-main\cataloguer.py:164: SyntaxWarning: invalid escape sequence '\{'
  logger.warning(f"Skipping shows\{torrent['filename']} since TMDB returned 0 results")
C:\Media-Server\Drive2CloudSync-main\cataloguer.py:271: SyntaxWarning: invalid escape sequence '\{'
  logger.warning(f"Skipping default\{torrent['filename']} since its an unknown entity")
C:\Media-Server\Drive2CloudSync-main\cataloguer.py:364: SyntaxWarning: invalid escape sequence '\{'
  logger.error(f"{type}\{torrent['filename']} could not be resolved\n\tDetails: {ex_string}")
C:\Media-Server\Drive2CloudSync-main\cataloguer.py:305: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).

**Comment by Tw1zT3d2four7** [comment]
this is when it stops/quits working

C:\Media-Server\Drive2CloudSync-main>python .\cataloguer.py -x
C:\Media-Server\Drive2CloudSync-main\cataloguer.py:48: SyntaxWarning: invalid escape sequence '\?'
  logger.warning(f"Skipping movies\??? since torrent object is empty")
C:\Media-Server\Drive2CloudSync-main\cataloguer.py:53: SyntaxWarning: invalid escape sequence '\{'
  logger.warning(f"Skipping movies\{torrent['filename']} since Real-Debrid API returned without relevant torrent info")
C:\Media-Server\Drive2CloudSync-main\cataloguer.py:76: SyntaxWarning: invalid escape sequence '\{'
  logger.warning(f"Skipping movies\{torrent['filename']} since TMDB returned 0 results")
C:\Media-Server\Drive2CloudSync-main\cataloguer.py:136: SyntaxWarning: invalid escape sequence '\?'
  logger.warning(f"Skipping shows\??? since torrent object is empty")
C:\Media-Server\Drive2CloudSync-main\cataloguer.py:141: SyntaxWarning: invalid escape sequence '\{'
  logger.warning(f"Skipping shows\{torrent['filename']} since Real-Debrid API returned without relevant torrent info")
C:\Media-Server\Drive2CloudSync-main\cataloguer.py:164: SyntaxWarning: invalid escape sequence '\{'
  logger.warning(f"Skipping shows\{torrent['filename']} since TMDB returned 0 results")
C:\Media-Server\Drive2CloudSync-main\cataloguer.py:271: SyntaxWarning: invalid escape sequence '\{'
  logger.warning(f"Skipping default\{torrent['filename']} since its an unknown entity")
C:\Media-Server\Drive2CloudSync-main\cataloguer.py:364: SyntaxWarning: invalid escape sequence '\{'
  logger.error(f"{type}\{torrent['filename']} could not be resolved\n\tDetails: {ex_string}")
C:\Media-Server\Drive2CloudSync-main\cataloguer.py:305: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  current_datetime = datetime.datetime.utcnow()
Traceback (most recent call last):
  File "C:\Media-Server\Drive2CloudSync-main\cataloguer.py", line 460, in <module>
    downloads = sort_downloads(get_downloads(200), downloads)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Media-Server\Drive2CloudSync-main\cataloguer.py", line 315, in sort_downloads
    _dict[download_info["link"]] = download_info
    ~~~~~^^^^^^^^^^^^^^^^^^^^^^^
TypeError: list indices must be integers or slices, not str

C:\Media-Server\Drive2CloudSync-main>pause
Press any key to continue . . .

**Comment by Tw1zT3d2four7** [comment]
also is there a docker image of this that would be great.

**Comment by Tw1zT3d2four7** [comment]
sorted the issues i had, but is there a docker image of this?

**Comment by honest-mule** [comment]
No, sorry. I'm closing this now, if you face any further issues you're welcome to start a new thread.
