### ISSUE TITLE
Unable to play in Plex

### ISSUE THREAD

**Issue by dreulavelle** [honest-mule/Drive2CloudSync#2]
You mentioned them playing just fine in Plex. Did you do anything differently to get the .strm files to play in Plex? I keep getting the error:

![image](https://github.com/honest-mule/Drive2CloudSync/assets/5782630/424e69e3-4bd0-4b19-b628-40976bfc89b9)

**Comment by honest-mule** [comment]
Sorry, I just checked, Plex is too limited to support the playback of `.strm` files. It was an oversight to mention it's name along with other media players that all have support for adding `.strm` files to your library.

I can suggest to not use Plex in this case, try Kodi or Emby.

However, if you're on PC then try this fork of rclone: https://github.com/itsToggle/rclone_RD

**Comment by dreulavelle** [comment]
Dang, thats a bummer! lol

I paid for Plex Pass and would prefer to use Plex over Jellyfin/Emby. I suppose I can fork and edit this to do symlinks instead of `.strm` files.

Also one thing to note, you don't need rclone if your just applying the http url to the file. You can retrieve that from the users account and then append `.strm` at the end of it to get the file name.. and then make the contents of the `.strm` file the direct url to the file. Scraping a users RD account rather than iterating over Rclone. 

One less cog in the wheel lol.

**Comment by honest-mule** [comment]
> Also one thing to note, you don't need rclone if your just applying the http url to the file

That's how this project started, but as my knowledge of real-debrid's API evolved and the more comfortable I got with it, I realized that this needs to be decoupled from the itsToggle's rclone fork. Now it fetches links and info directly from your source account using the raw real-debrid API.
